[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo done"

[functions]
  node_bundler = "esbuild"

[functions."search"]
  timeout = 26

[functions."schedule"]
  timeout = 26
